Check for github-creds file

diff --git a/get-repos b/get-repos
--- a/get-repos
+++ b/get-repos
@@ -42,6 +42,11 @@ if [[ $# -lt 1 ]]; then
   exit 1
 fi
 
+if ! grep -q ":" ~/.github-creds 2>/dev/null; then
+  echo "Error: must create ~/.github-creds file containing USER:TOKEN" >&2
+  exit 1
+fi
+
 repo_dir="$1"
 mkdir -p "$repo_dir"
 
